### ISSUE TITLE
Ability to persist on submit, if needed

### ISSUE THREAD

**Issue by cloud-walker** [jaredpalmer/formik-persist#3]
I've got a form which will be used in multiple pages, with different persistence needs.

You think It could be a thing to tweak `formik-persist` behaviour to for example persist on submit, based on a prop for example?

**Comment by cloud-walker** [comment]
Maybe for now I can for example render <Persist ..> only if formik is in `isSubmitting` state 🤔

**Comment by wasimsheikh1** [comment]
@jaredpalmer & @cloud-walker .I too wanted this feature..can anyone help me in it.

**Comment by cloud-walker** [comment]
With the advent of react hooks and formik 2, I don't think this is worth it anymore..
